### ISSUE TITLE
Attachment of deployment artifacts

### ISSUE THREAD

**Issue by mbeisel** [SeQuenC-Consortium/.github#1]
---

## Problem Statement

It shall be possible to attachment docker image reference and source files (e.g., zip containing python files, requirements, ...).

## Sketch

![Image](https://user-images.githubusercontent.com/19931367/233973016-b4929c9c-f24e-408e-8f81-3f9d78a2dc1c.png)

## References

Documentation included in WF Modeler.

## Expected Behavior

Deployment Files can be uploaded in modeler.

## Tasks

- [ ] Add deployment property to activities
- [ ] Add button for deployment to task palette
- [ ] Add a dialog where users can upload their deployment files / dockerhub reference.

## Notes

The uploaded files shall be deployed via OpenTOSCA.

---
